remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Parons' Problems 2023 ITICSE Working Group
description: This site provides a draft of the working group paper and other auxilliary materials from the 2023 ITICSE Parsons Problems Working Group
